deploy: 2b09255a2cbb41c2acd2de5f1175f2edc700db01

diff --git a/target/executable/datasets/loaders/allen_brain_cell_atlas/allen_brain_cell_atlas b/target/executable/datasets/loaders/allen_brain_cell_atlas/allen_brain_cell_atlas
--- a/target/executable/datasets/loaders/allen_brain_cell_atlas/allen_brain_cell_atlas
+++ b/target/executable/datasets/loaders/allen_brain_cell_atlas/allen_brain_cell_atlas
@@ -207,6 +207,11 @@ function ViashHelp {
   echo "        example: 123"
   echo "        A seed for the subsampling."
   echo ""
+  echo "Caching settings:"
+  echo "    --keep_files"
+  echo "        type: boolean, required parameter"
+  echo "        Whether to remove the downloaded files after processing."
+  echo ""
   echo "Metadata:"
   echo "    --dataset_id"
   echo "        type: string, required parameter"
@@ -527,9 +532,9 @@ RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "git+https://github.com/alleninstitute/abc_atlas_access"
 
 LABEL org.opencontainers.image.description="Companion container for running component datasets/loaders allen_brain_cell_atlas"
-LABEL org.opencontainers.image.created="2024-09-25T20:40:19Z"
+LABEL org.opencontainers.image.created="2024-09-26T01:01:06Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_ist_preprocessing"
-LABEL org.opencontainers.image.revision="28d7183da03e1d1582d04d3c90b35c85dae55358"
+LABEL org.opencontainers.image.revision="2b09255a2cbb41c2acd2de5f1175f2edc700db01"
 LABEL org.opencontainers.image.version="build_main"
 
 VIASHDOCKER
@@ -739,6 +744,17 @@ while [[ $# -gt 0 ]]; do
         --sample_seed=*)
             [ -n "$VIASH_PAR_SAMPLE_SEED" ] && ViashError Bad arguments for option \'--sample_seed=*\': \'$VIASH_PAR_SAMPLE_SEED\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_SAMPLE_SEED=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --keep_files)
+            [ -n "$VIASH_PAR_KEEP_FILES" ] && ViashError Bad arguments for option \'--keep_files\': \'$VIASH_PAR_KEEP_FILES\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_KEEP_FILES="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --keep_files. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --keep_files=*)
+            [ -n "$VIASH_PAR_KEEP_FILES" ] && ViashError Bad arguments for option \'--keep_files=*\': \'$VIASH_PAR_KEEP_FILES\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_KEEP_FILES=$(ViashRemoveFlags "$1")
             shift 1
             ;;
         --dataset_id)
@@ -1001,6 +1017,10 @@ fi
 
 
 # check whether required parameters exist
+if [ -z ${VIASH_PAR_KEEP_FILES+x} ]; then
+  ViashError '--keep_files' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_PAR_DATASET_ID+x} ]; then
   ViashError '--dataset_id' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -1064,6 +1084,12 @@ fi
 if [[ -n "$VIASH_PAR_SAMPLE_SEED" ]]; then
   if ! [[ "$VIASH_PAR_SAMPLE_SEED" =~ ^[-+]?[0-9]+$ ]]; then
     ViashError '--sample_seed' has to be an integer. Use "--help" to get more information on the parameters.
+    exit 1
+  fi
+fi
+if [[ -n "$VIASH_PAR_KEEP_FILES" ]]; then
+  if ! [[ "$VIASH_PAR_KEEP_FILES" =~ ^(true|True|TRUE|false|False|FALSE|yes|Yes|YES|no|No|NO)$ ]]; then
+    ViashError '--keep_files' has to be a boolean. Use "--help" to get more information on the parameters.
     exit 1
   fi
 fi
@@ -1273,6 +1299,7 @@ par = {
   'sample_obs_weight': $( if [ ! -z ${VIASH_PAR_SAMPLE_OBS_WEIGHT+x} ]; then echo "r'${VIASH_PAR_SAMPLE_OBS_WEIGHT//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'sample_transform': $( if [ ! -z ${VIASH_PAR_SAMPLE_TRANSFORM+x} ]; then echo "r'${VIASH_PAR_SAMPLE_TRANSFORM//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'sample_seed': $( if [ ! -z ${VIASH_PAR_SAMPLE_SEED+x} ]; then echo "int(r'${VIASH_PAR_SAMPLE_SEED//\'/\'\"\'\"r\'}')"; else echo None; fi ),
+  'keep_files': $( if [ ! -z ${VIASH_PAR_KEEP_FILES+x} ]; then echo "r'${VIASH_PAR_KEEP_FILES//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
   'dataset_id': $( if [ ! -z ${VIASH_PAR_DATASET_ID+x} ]; then echo "r'${VIASH_PAR_DATASET_ID//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'dataset_name': $( if [ ! -z ${VIASH_PAR_DATASET_NAME+x} ]; then echo "r'${VIASH_PAR_DATASET_NAME//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'dataset_url': $( if [ ! -z ${VIASH_PAR_DATASET_URL+x} ]; then echo "r'${VIASH_PAR_DATASET_URL//\'/\'\"\'\"r\'}'"; else echo None; fi ),
@@ -1324,8 +1351,9 @@ abc_cache.load_manifest(
 )
 
 print("Reading obs", flush=True)
+obs_path = abc_cache.get_metadata_path(directory="WMB-10X", file_name="cell_metadata_with_cluster_annotation")
 obs = pd.read_csv(
-    abc_cache.get_metadata_path(directory="WMB-10X", file_name="cell_metadata_with_cluster_annotation"),
+    obs_path,
     index_col=0,
     dtype=defaultdict(
         lambda: "category",
@@ -1335,6 +1363,8 @@ obs = pd.read_csv(
         region_of_interest_order="int"
     )
 )
+if not par["keep_files"]:
+    obs_path.unlink()
 
 print("Filtering obs based on regions", flush=True)
 obs = obs[obs["anatomical_division_label"].isin(REGIONS)]
@@ -1368,6 +1398,9 @@ for region in REGIONS:
 
         print(f"Reading h5ad for region {region}", flush=True)
         adata = ad.read_h5ad(str(adata_path))
+
+        if not par["keep_files"]:
+            adata_path.unlink()
 
         # filter cells
         adata = adata[adata.obs_names.isin(obs.index)].copy()
